### ISSUE TITLE
Query SQL should be checked into the repository

### ISSUE THREAD

**Issue by fleupold** [Mefiseru/MEVGuard-Open-Source-MEV-Blocker-Verification-Tool#2]
We shouldn't rely on a hardcoded query id which is owned by an uncorrelated account. Instead, we should create a new query from scratch with SQL that is checked into the codebase.

**Comment by rylaix** [comment]
Included the check for SQL query, and the query itself in "queries" folder.

**Comment by fleupold** [comment]
But the script is still using the hardcoded query id, isn't it? Can you make it so that it updates the query with the SQL that is checked into the repository so that we know the script is running on the correct SQL and not some manually changed version?

**Comment by rylaix** [comment]
> But the script is still using the hardcoded query id, isn't it? Can you make it so that it updates the query with the SQL that is checked into the repository so that we know the script is running on the correct SQL and not some manually changed version?

Hello!
Checked carefully Dune API docs. It doesn't support RAW SQL execution, or even update query via api. But we can use the approach of check if the query sql is the same as in the repo (as Already did, and as dune doesn't give the ability to anyone rather the author to change the quer, I think it's not needed).
Anyway, If script will find any issues in queries (are not the same, for example), it will make report and abort.

**Comment by fleupold** [comment]
Sounds good, thank you!
