### ISSUE TITLE
Incorrect query

### ISSUE THREAD

**Issue by fleupold** [Mefiseru/MEVGuard-Open-Source-MEV-Blocker-Verification-Tool#3]
The [used query](https://dune.com/queries/2446884) is fetching all landed user and searcher transaction since 2023-04-24.

Instead, it should:
- Fetch all submitted backruns (even the ones that didn't make it on chain)
- Not only collect their transaction hash, but all signed transaction parameters (to, from, gas, calldata, etc), so that they can be simulated in milestone 2.
- Filter on block number or some other much smaller subset to avoid using a ton of credits (it also doesn't make sense to run the same query multiple times in parallel, cf. screenshot)
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/b85ac8f6-5a65-46ea-bc49-98eaa0d8cdbd">

**Comment by fleupold** [comment]
Regarding the exact filter, I'm not yet sure I understand how the data gathering script is supposed to be used. If we intend to always run it on a range of blocks (e.g. the last hours), then I'd suggest to make the query mimic that intended range so we can have one query per run of the data fetching script (currently it uses the last 5 blocks, which seems a bit arbitrary).

I think ideally, it would backfill based off a start date and the data that it can find in the `/data` folder (or DB)

**Comment by rylaix** [comment]
As mentioned on the forum, the multiprocessing issue was fixed in the hotfix. You were running older version.
Also, Asked a question exactly about the SQL itself on the forum

**Comment by fleupold** [comment]
Copying from forum (let's keep technical discussions on github)

> In the main Scope of work provided by [@middleway.eth](https://forum.cow.fi/u/middleway.eth) was written that I must only gather information inside the block itself.
In your github issue you asked me to “Fetch all submitted backruns (even the ones that didn’t make it on chain)”.
This clearly increases the amount of work which I have to do, and time too (As I have to collect the mempool which is outside the backrun, and are not being collected by Dune), So I have to:
Make my own service which will periodically check the node directly
Or use flashbots.

I think there is a misunderstanding here. What I'm asking should not create significantly more work. You can find all the submitted backruns in Dune. Check e.g. this [example query](https://dune.com/queries/3114264) for how to fetch all bundles that were submitted for a given transaction.

I think all you need to do is adapt the query to run for a range of blocks and fetch all bundles instead of the data you are currently fetching.

It's totally fine to only focus on target (ie user) transactions that actually made it on chain, however in order to assess whether the builder performed optimal bundle merging (which is the main goal of this work) you need to simulate all bundles that were submitted.
This is because the winning block may have censored valid bundles that would have refunded the user otherwise. Builders can do that to include non MEV Blocker backruns that increase the value of the block but don't refund the user.

Specifically, the [original specification](https://forum.cow.fi/t/rfp-02-mev-blocker-bundle-merging-tracker/2504) referred to this point as 

> Track all bundles related to this transaction that were broadcasted within the first 10 seconds prior to the block time (configurable).

I hope this is doable without creating much more work.

**Comment by rylaix** [comment]
Before opening a pull request, I want to ensure some additional info:

Should I add any specific logic to the query to handle edge cases (unusual structures in blocks,  very high or low transaction counts), or should this be managed by the data processing script in Python?

Related to the above: Should the query include any mechanisms to retry on failure, or should this be entirely managed by the Python script?

Are there any specific parameters or conditions under which these backruns should be filtered? Should we focus only on specific types of transactions or builders? (As mentioned before, we must to gather all information possible, even which is outside of the Chain. Must we include any simulation specific parameters only, or gather as much as possible?)

**Comment by fleupold** [comment]
How can an SQL query itself retry on failure? I think the data is either available in Dune or it is not (it is inserted with a ~30s delay). If it isn't yet synced, the python script should either retry or fail and ask to be configured in a way (by running with enough delay behind the tip of the chain) to ensure the data that is intended to be fetched is synced.

High/low bundle count should be handled (I think we have some transaction with ~1000 backruns, a lot of transactions have no backruns at all).

We can exclude any backruns that were sent for transactions which didn't end up in any block (e.g. cancelled or failed txs) or that were broadcasted for blocks in which the target transaction didn't get included. However, for every transaction t in block b, we need to gather all bundles that were submitted for t in b. This is to ensure that the following milestones can be implemented according to the grant proposal.

All information that is then required to simulate each backrun should already be part of the table that I linked you in the query above, so storing the raw bundle json + all other transactions in the block (which you already do) should be sufficient.

**Comment by rylaix** [comment]
Hello!
I've added a test SQL query to the [test branch](https://github.com/Mefiseru/MEVGuard-Open-Source-MEV-Blocker-Verification-Tool/blob/tests/queries/fetch_backruns.sql).
At this moment, is a draft without optimization. I've tried to find whatever related to mempool in Dune, Buto found Only a Dumpster from Dune devs (which are simply saved files and are not useful for us), and a `mmpool_trades` in data explorer.
Are we good to go with the last mentioned?
Also, So sorry for the confusion about SQL, I'm sick right now and I forgot to delete it

**Comment by fleupold** [comment]
> I've tried to find whatever related to mempool in Dune

Can you explain why you need access to the mempool?

You have access to all broadcasted mevblocker transactions for a given block using `mevblocker.raw_bundles` and have access to all landed transactions via `ethereum.transactions`. If you join the two you should be able to get what we discussed:

>  for every transaction t in block b, we need to gather all bundles that were submitted for t in b.

If you make your work a PR instead of a branch, I can comment inline on the query to give feedback (e.g. I would restrict the range on blocks instead of timestamps).

**Comment by rylaix** [comment]
> Can you explain why you need access to the mempool?

Normally, when You're trying to access data off-chain, you'll need to gather mempool.

> If you make your work a PR instead of a branch

Succsessfully [Created!](https://github.com/Mefiseru/MEVGuard-Open-Source-MEV-Blocker-Verification-Tool/pull/7)
