### ISSUE TITLE
Polling interval is too long and should be configurable

### ISSUE THREAD

**Issue by fleupold** [Mefiseru/MEVGuard-Open-Source-MEV-Blocker-Verification-Tool#6]
Waiting 9 minutes for a single query execution is too long (especially if the goal of this program is to eventually run in real time). It should at least not be hard coded but instead made configurable.

**Comment by rylaix** [comment]
Made both of things. Thanks for the point!

**Comment by fleupold** [comment]
Do you have a PR for this? I cannot find the new config documented in the readme?

**Comment by rylaix** [comment]
> Do you have a PR for this? I cannot find the new config documented in the readme?

Yeah, it documented in "config.yaml".
`polling_rate_minutes: 2 # Polling interval in minutes`

**Comment by fleupold** [comment]
Can we make it in seconds please? With a pro account I expect the queries to run within seconds, so we should be able to check more often than once a minute.

**Comment by rylaix** [comment]
Ofc! Pushed a commit with changes.

**Comment by fleupold** [comment]
Thanks!

Just as a general process comment, if you can make your changes PRs (no need to wait for review) it makes it very easy for people that watch this repository to track the diffs.

**Comment by rylaix** [comment]
Oh, I forgot. Thanks for the reminder.
